package com.RafaelDiaz.ClubJudoColombia.modelo.enums;

public enum TipoSesion {
    ENTRENAMIENTO, RANDORI, SHIAI, TECNICA,
    ACONDICIONAMIENTO, PESAS, MONDO,
    EVALUACION, UCHIKOMI, NAGEKOMI, KAKARIGEIKO, YAKUSOKUGEIKO
}