
    create table asistencias (
        latitud DOUBLE PRECISION,
        longitud DOUBLE PRECISION,
        id_asistencia bigint generated by default as identity,
        id_judoka bigint not null,
        id_sesion_ejecutada bigint not null,
        notas varchar(255),
        estado VARCHAR(50) not null,
        primary key (id_asistencia)
    );

    create table campos_entrenamiento (
        completado BOOLEAN not null,
        fecha_fin date not null,
        fecha_inicio date not null,
        puntos_ascenso integer not null,
        id bigint generated by default as identity,
        id_judoka bigint not null,
        nombre varchar(255) not null,
        objetivo varchar(255),
        ubicacion varchar(255),
        primary key (id)
    );

    create table comentarios (
        fecha TIMESTAMP,
        id bigint generated by default as identity,
        id_autor bigint not null,
        id_publicacion bigint not null,
        contenido TEXT not null,
        primary key (id)
    );

    create table competencia_requisitos (
        id_competencia bigint not null,
        nombre_requisito varchar(255)
    );

    create table competencias (
        fecha_fin date,
        fecha_inicio date not null,
        id bigint generated by default as identity,
        lugar varchar(255) not null,
        nombre varchar(255) not null,
        nivel VARCHAR(50) not null,
        primary key (id)
    );

    create table conceptos_financieros (
        valor_sugerido numeric(38,2),
        id bigint generated by default as identity,
        nombre varchar(255) not null unique,
        tipo VARCHAR(50) not null,
        primary key (id)
    );

    create table configuracion_sistema (
        comision_sensei_mensualidad numeric(38,2),
        fin_alquiler_judogi_anual numeric(38,2),
        fin_dia_cobro_mensual numeric(38,2),
        fin_dia_vencimiento numeric(38,2),
        fin_matricula_anual numeric(38,2),
        fin_saas_canon_fijo numeric(38,2),
        fin_saas_comision_club numeric(38,2),
        fin_sensei_master_mensualidad numeric(38,2),
        grupo_comision_default numeric(10,2),
        grupo_dias_gracia_default integer,
        grupo_incluye_matricula_default BOOLEAN,
        grupo_monto_matricula_default numeric(10,2),
        grupo_tarifa_default numeric(10,2),
        precio_minimo_mensual numeric(10,2),
        sec_token_expiracion_hs numeric(38,2),
        tarifa_minima_global numeric(10,2),
        id bigint not null,
        email_soporte varchar(255),
        moneda varchar(255),
        nombre_organizacion varchar(255) not null,
        telefono_contacto varchar(255),
        url_logo varchar(255),
        nivel VARCHAR(50) not null,
        primary key (id)
    );

    create table cuentas_cobro (
        fecha_generacion date not null,
        fecha_vencimiento date not null,
        valor_comision_sensei numeric(38,2),
        valor_total numeric(38,2) not null,
        id bigint generated by default as identity,
        id_judoka bigint not null,
        id_usuario_responsable bigint not null,
        concepto varchar(255) not null,
        estado VARCHAR(50) not null,
        primary key (id)
    );

    create table documentos_requisitos (
        validado_por_sensei BOOLEAN not null,
        fecha_carga TIMESTAMP,
        id bigint generated by default as identity,
        id_judoka bigint not null,
        url_archivo varchar(2048) not null,
        evento_asociado varchar(255),
        tipo VARCHAR(50) not null,
        primary key (id)
    );

    create table ejecuciones_tareas (
        completado BOOLEAN not null,
        latitud DOUBLE PRECISION,
        longitud DOUBLE PRECISION,
        fecha_registro TIMESTAMP not null,
        id_ejecucion bigint generated by default as identity,
        id_ejercicio_plan bigint not null,
        id_judoka bigint not null,
        primary key (id_ejecucion)
    );

    create table ejercicios_planificados (
        duracion_minutos integer,
        intensidad integer,
        orden_ejecucion integer,
        requiere_supervision BOOLEAN not null,
        id_ejercicio_plan bigint generated by default as identity,
        id_judoka_asignado bigint,
        id_microciclo bigint not null,
        id_prueba_estandar bigint,
        id_tarea_diaria bigint,
        nota_ajuste varchar(255),
        notas_sensei varchar(255),
        primary key (id_ejercicio_plan)
    );

    create table grupo_dias (
        id_grupo bigint not null,
        dia VARCHAR(50)
    );

    create table grupos_entrenamiento (
        comision_sensei numeric(10,2) not null,
        dias_gracia integer not null,
        es_tarifario BOOLEAN not null,
        hora_fin TIME,
        hora_inicio TIME,
        incluye_matricula BOOLEAN not null,
        latitud DOUBLE PRECISION,
        longitud DOUBLE PRECISION,
        monto_matricula numeric(10,2),
        radio_permitido_metros integer,
        tarifa_mensual numeric(10,2) not null,
        id_grupo bigint generated by default as identity,
        id_sensei bigint not null,
        lugar_practica varchar(150),
        nombre varchar(150) not null unique,
        descripcion varchar(255),
        primary key (id_grupo)
    );

    create table insignias (
        nivel_requerido integer,
        id_insignia bigint generated by default as identity,
        clave varchar(255),
        descripcion varchar(255),
        icono_vaadin varchar(255),
        nombre varchar(255),
        categoria VARCHAR(50),
        primary key (id_insignia)
    );

    create table inventario_articulos (
        cantidad_stock integer not null,
        precio_costo numeric(38,2) not null,
        precio_venta numeric(38,2) not null,
        stock_minimo_alerta integer not null,
        id bigint generated by default as identity,
        descripcion varchar(255),
        nombre varchar(255) not null,
        primary key (id)
    );

    create table judoka_grupos (
        id_grupo bigint not null,
        id_judoka bigint not null,
        primary key (id_grupo, id_judoka)
    );

    create table judoka_insignias (
        fecha_obtencion TIMESTAMP,
        id_insignia bigint,
        id_judoka bigint,
        id_logro bigint generated by default as identity,
        id_sensei bigint,
        primary key (id_logro)
    );

    create table judokas (
        es_competidor_activo BOOLEAN,
        es_mayor_edad BOOLEAN,
        estatura_cm DOUBLE PRECISION,
        fecha_devolucion_judogi date,
        fecha_nacimiento date,
        fecha_vencimiento_suscripcion date,
        matricula_pagada BOOLEAN,
        monto_mensualidad numeric(38,2),
        peso_kg DOUBLE PRECISION,
        suscripcion_activa BOOLEAN,
        tiene_judogi_alquilado BOOLEAN,
        fecha_generacion_token TIMESTAMP,
        id_acudiente bigint not null,
        id_grupo bigint,
        id_grupo_facturacion bigint,
        id_judoka bigint generated by default as identity,
        id_mecenas bigint,
        id_sensei bigint not null,
        celular varchar(13),
        telefono_acudiente varchar(20),
        eps varchar(100),
        ocupacion_principal varchar(200),
        apellido_atleta varchar(255),
        nombre_acudiente varchar(255),
        nombre_atleta varchar(255),
        nombre_contacto_emergencia varchar(255),
        ruta_autorizacion_waiver varchar(255),
        ruta_certificado_eps varchar(255),
        telefono_emergencia varchar(255),
        token_acceso_directo varchar(255) unique,
        estado VARCHAR(50),
        grado_cinturon VARCHAR(50),
        palmares CLOB,
        sexo VARCHAR(50),
        url_foto_perfil CLOB,
        primary key (id_judoka)
    );

    create table macrociclos (
        fecha_fin date,
        fecha_inicio date,
        id_macrociclo bigint generated by default as identity,
        id_sensei bigint not null,
        nombre varchar(150) not null,
        objetivo_principal varchar(255),
        primary key (id_macrociclo)
    );

    create table mecenas (
        id_mecenas bigint generated by default as identity,
        id_usuario bigint not null unique,
        nit_empresa varchar(50),
        nombre_empresa varchar(255),
        descripcion_patrocinio CLOB,
        tipo_mecenas VARCHAR(50) not null,
        primary key (id_mecenas)
    );

    create table mensajes_chat (
        fecha TIMESTAMP,
        id bigint generated by default as identity,
        id_autor bigint not null,
        id_sensei bigint not null,
        contenido TEXT not null,
        primary key (id)
    );

    create table metricas (
        es_calculada BOOLEAN not null,
        id_metrica bigint generated by default as identity,
        unidad varchar(10) not null,
        nombre_key varchar(255) not null unique,
        primary key (id_metrica)
    );

    create table microciclo_grupos (
        id_grupo bigint not null,
        id_microciclo bigint not null,
        primary key (id_grupo, id_microciclo)
    );

    create table microciclo_pruebas (
        id_microciclo bigint not null,
        id_prueba bigint not null,
        primary key (id_microciclo, id_prueba)
    );

    create table microciclos (
        fecha_fin date,
        fecha_inicio date,
        id_macrociclo bigint,
        id_microciclo bigint generated by default as identity,
        id_sensei bigint not null,
        nombre_microciclo varchar(150) not null,
        estado VARCHAR(50) not null,
        mesociclo_atc VARCHAR(50),
        tipo_microciclo VARCHAR(50),
        primary key (id_microciclo)
    );

    create table movimientos_caja (
        monto numeric(38,2) not null,
        fecha TIMESTAMP not null,
        id bigint generated by default as identity,
        id_concepto bigint not null,
        id_judoka bigint,
        observacion TEXT,
        registrado_por varchar(255),
        url_soporte varchar(255),
        metodo_pago VARCHAR(50) not null,
        tipo VARCHAR(50) not null,
        primary key (id)
    );

    create table normas_evaluacion (
        edad_max integer not null,
        edad_min integer not null,
        valor_max DOUBLE PRECISION,
        valor_min DOUBLE PRECISION,
        id_ejercicio bigint not null,
        id_metrica bigint not null,
        id_norma bigint generated by default as identity,
        fuente varchar(100) not null,
        clasificacion VARCHAR(50) not null,
        sexo VARCHAR(50) not null,
        primary key (id_norma)
    );

    create table pagos (
        monto_cop DOUBLE PRECISION not null,
        fecha_creacion TIMESTAMP not null,
        fecha_pago_exitoso TIMESTAMP,
        id_cuenta_cobro bigint unique,
        id_pago bigint generated by default as identity,
        id_producto bigint,
        id_usuario bigint not null,
        url_comprobante varchar(500),
        estado VARCHAR(50) not null,
        metodo_pago VARCHAR(50) not null,
        primary key (id_pago)
    );

    create table palmares (
        fecha date,
        id bigint generated by default as identity,
        id_competencia bigint,
        id_judoka bigint not null,
        nombre_campeonato varchar(255),
        sede varchar(255),
        url_foto varchar(255),
        url_video varchar(255),
        nivel VARCHAR(50),
        resultado VARCHAR(50),
        primary key (id)
    );

    create table plan_tarea_dias (
        id_ejercicio_plan bigint not null,
        dia_semana VARCHAR(50)
    );

    create table productos (
        activo BOOLEAN not null,
        precio_cop DOUBLE PRECISION not null,
        id_producto bigint generated by default as identity,
        stripe_price_id varchar(100) unique,
        nombre varchar(150) not null,
        descripcion varchar(255),
        tipo_subscripcion VARCHAR(50) not null,
        primary key (id_producto)
    );

    create table prueba_estandar_metricas (
        id_ejercicio bigint not null,
        id_metrica bigint not null,
        primary key (id_ejercicio, id_metrica)
    );

    create table pruebas_estandar (
        es_global BOOLEAN not null,
        id_ejercicio bigint generated by default as identity,
        id_sensei_creador bigint,
        nombre_key varchar(200) unique,
        nombre_personalizado varchar(200),
        video_url varchar(255),
        categoria VARCHAR(50) not null,
        descripcion_key CLOB,
        descripcion_personalizada CLOB,
        formula_calculo VARCHAR(50) not null,
        objetivo_key CLOB,
        objetivo_personalizado CLOB,
        primary key (id_ejercicio)
    );

    create table publicaciones (
        likes integer not null,
        fecha TIMESTAMP,
        id bigint generated by default as identity,
        id_autor bigint not null,
        id_sensei bigint not null,
        contenido TEXT,
        imagen_url varchar(255),
        primary key (id)
    );

    create table reflexiones (
        fecha_creacion TIMESTAMP not null,
        fecha_ultima_edicion TIMESTAMP not null,
        id bigint generated by default as identity,
        id_judoka bigint not null,
        contenido CLOB not null,
        primary key (id)
    );

    create table reglas_gamificacion (
        valor_objetivo numeric(10,2),
        id bigint generated by default as identity,
        insignia_id bigint not null,
        metrica_id bigint,
        sensei_id bigint not null,
        descripcion varchar(255),
        operador VARCHAR(50) not null,
        tipo_evento VARCHAR(50) not null,
        primary key (id)
    );

    create table resultados_pruebas (
        numero_intento integer,
        valor DOUBLE PRECISION not null,
        fecha_registro TIMESTAMP not null,
        id_ejercicio_plan bigint not null,
        id_judoka bigint not null,
        id_metrica bigint not null,
        id_resultado bigint generated by default as identity,
        notas_judoka varchar(255),
        primary key (id_resultado)
    );

    create table roles (
        id_rol bigint generated by default as identity,
        nombre varchar(50) not null unique,
        primary key (id_rol)
    );

    create table senseis (
        anos_practica integer,
        comision_porcentaje numeric(5,2),
        es_club_propio BOOLEAN not null,
        saldo_wallet numeric(38,2),
        total_ganado_historico numeric(38,2),
        id_sensei bigint generated by default as identity,
        id_usuario bigint not null unique,
        nombre_dojo varchar(100),
        nombre_club varchar(150),
        url_foto_perfil varchar(1000),
        datos_bancarios_nequi varchar(255),
        ruta_certificaciones_archivo varchar(255),
        biografia CLOB,
        grado_cinturon VARCHAR(50) not null,
        primary key (id_sensei)
    );

    create table sesiones_ejecutadas (
        latitud DOUBLE PRECISION,
        longitud DOUBLE PRECISION,
        radio_permitido_metros integer,
        fecha_hora_ejecucion TIMESTAMP not null,
        id_grupo bigint not null,
        id_microciclo bigint not null,
        id_sensei bigint not null,
        id_sesion_ejecutada bigint generated by default as identity,
        notas_retroalimentacion varchar(1000),
        primary key (id_sesion_ejecutada)
    );

    create table sesiones_programadas (
        latitud DOUBLE PRECISION,
        longitud DOUBLE PRECISION,
        radio_permitido_metros integer,
        fecha_hora_fin TIMESTAMP not null,
        fecha_hora_inicio TIMESTAMP not null,
        id_grupo bigint not null,
        id_sensei bigint not null,
        id_sesion bigint generated by default as identity,
        version bigint not null,
        nombre varchar(255) not null,
        tipo_sesion VARCHAR(50) not null,
        primary key (id_sesion)
    );

    create table tareas_diarias (
        id_sensei bigint,
        id_tarea bigint generated by default as identity,
        meta_texto varchar(255),
        nombre varchar(255) not null,
        video_url varchar(255),
        categoria VARCHAR(50) not null,
        descripcion CLOB,
        primary key (id_tarea)
    );

    create table tokens_invitacion (
        es_club_propio BOOLEAN,
        porcentaje_comision numeric(5,2),
        usado BOOLEAN not null,
        fecha_creacion TIMESTAMP not null,
        fecha_expiracion TIMESTAMP not null,
        id bigint generated by default as identity,
        id_grupo bigint,
        id_judoka bigint unique,
        id_sensei bigint,
        id_usuario bigint,
        token varchar(36) not null unique,
        rol_esperado varchar(50),
        primary key (id)
    );

    create table traducciones (
        idioma varchar(5) not null,
        id bigint generated by default as identity,
        clave varchar(255) not null,
        texto CLOB not null,
        primary key (id),
        unique (clave, idioma)
    );

    create table usuarios (
        activo BOOLEAN not null,
        id_grupo_tarifario bigint,
        id_sensei_invitador bigint,
        id_usuario bigint generated by default as identity,
        celular varchar(20),
        username varchar(100) not null unique,
        apellido varchar(150) not null,
        email varchar(150),
        nombre varchar(150) not null,
        password_hash varchar(255) not null,
        primary key (id_usuario)
    );

    create table usuarios_roles (
        id_rol bigint not null,
        id_usuario bigint not null,
        primary key (id_rol, id_usuario)
    );

    create index idx_asistencia_judoka 
       on asistencias (id_judoka);

    create index idx_asistencia_sesion 
       on asistencias (id_sesion_ejecutada);

    create index idx_asistencia_estado 
       on asistencias (estado);

    create index idx_judoka_acudiente 
       on judokas (id_acudiente);

    create index idx_judoka_sensei 
       on judokas (id_sensei);

    create index idx_judoka_grupo 
       on judokas (id_grupo);

    create index idx_judoka_estado 
       on judokas (estado);

    create index idx_judoka_suscripcion 
       on judokas (suscripcion_activa);

    create index idx_movimiento_fecha 
       on movimientos_caja (fecha);

    create index idx_movimiento_concepto 
       on movimientos_caja (id_concepto);

    create index idx_movimiento_judoka 
       on movimientos_caja (id_judoka);

    create index idx_movimiento_tipo 
       on movimientos_caja (tipo);

    create index idx_pago_usuario 
       on pagos (id_usuario);

    create index idx_pago_producto 
       on pagos (id_producto);

    create index idx_pago_estado 
       on pagos (estado);

    create index idx_pago_fecha 
       on pagos (fecha_creacion);

    alter table if exists asistencias 
       add constraint FKtjyknlflm6ijpuhso55wdy5sx 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists asistencias 
       add constraint FKhvbhk7ociqqpusky89q9oibu3 
       foreign key (id_sesion_ejecutada) 
       references sesiones_ejecutadas;

    alter table if exists campos_entrenamiento 
       add constraint FKnaj9xdwp9fyjjc0cy67vnck17 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists comentarios 
       add constraint FKmt1o5metpcn30lk0x23xhyrfa 
       foreign key (id_autor) 
       references usuarios;

    alter table if exists comentarios 
       add constraint FK9g1lv5mtbiv9lfm7xqdd5crxw 
       foreign key (id_publicacion) 
       references publicaciones;

    alter table if exists competencia_requisitos 
       add constraint FKtbmm3u93cwo4dk85k9dxfbs0q 
       foreign key (id_competencia) 
       references competencias;

    alter table if exists cuentas_cobro 
       add constraint FKjp4jnafp6egxpslej8xm34e4q 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists cuentas_cobro 
       add constraint FKg0bsmii685ioxbg1o1u1nmcwx 
       foreign key (id_usuario_responsable) 
       references usuarios;

    alter table if exists documentos_requisitos 
       add constraint FKbwc6mudypylrk09a6b7p4y3cc 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists ejecuciones_tareas 
       add constraint FKsa2vaw2xnf045i3wl2q6vse5d 
       foreign key (id_ejercicio_plan) 
       references ejercicios_planificados;

    alter table if exists ejecuciones_tareas 
       add constraint FKcc20j2fk11q9i871yk4o8r23g 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists ejercicios_planificados 
       add constraint FKc8pny2yfp6l3br6nf2ean3y99 
       foreign key (id_judoka_asignado) 
       references judokas;

    alter table if exists ejercicios_planificados 
       add constraint FKyycdi0tt5al90a7fjqw82qo8 
       foreign key (id_microciclo) 
       references microciclos;

    alter table if exists ejercicios_planificados 
       add constraint FKa26486vod49lkh3rv8e4vnp1j 
       foreign key (id_prueba_estandar) 
       references pruebas_estandar;

    alter table if exists ejercicios_planificados 
       add constraint FKjpr18qyejxsf9ld01gwyb5py7 
       foreign key (id_tarea_diaria) 
       references tareas_diarias;

    alter table if exists grupo_dias 
       add constraint FK9vl618u50x4gjshy32fypxoo6 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists grupos_entrenamiento 
       add constraint FKlr9xylprnw4ttiirscm5w4by1 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists judoka_grupos 
       add constraint FKq1fetssx3641hb3jc3d6ngyco 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists judoka_grupos 
       add constraint FKsdeuv2k7n17imbabfh9nro6na 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists judoka_insignias 
       add constraint FKmi8jnvfk8iukwypl77l401ygu 
       foreign key (id_insignia) 
       references insignias;

    alter table if exists judoka_insignias 
       add constraint FK4cx6kql0pwtwhgk903kgrq7ur 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists judoka_insignias 
       add constraint FKk2ebsvrdy5n35on8v4j43kwlq 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists judokas 
       add constraint FKg0ftyit7hk34027m7gcldeb7v 
       foreign key (id_acudiente) 
       references usuarios;

    alter table if exists judokas 
       add constraint FK6af2oweprajh12t3mbm9kgm7b 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists judokas 
       add constraint FKr30dx3mnu7b8gg4t0h805o4m9 
       foreign key (id_grupo_facturacion) 
       references grupos_entrenamiento;

    alter table if exists judokas 
       add constraint FKhfnay8t32kh42rw0g7847lbss 
       foreign key (id_mecenas) 
       references mecenas;

    alter table if exists judokas 
       add constraint FKau2n9u7o7slq16jvgpk6qisd4 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists macrociclos 
       add constraint FKm1jloy5q611malm2dy3p0c2s5 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists mecenas 
       add constraint FKkyqblvntxsn9voc9e6yd5qoyx 
       foreign key (id_usuario) 
       references usuarios;

    alter table if exists mensajes_chat 
       add constraint FKr4go20a7cornbsc3pdnccuupj 
       foreign key (id_autor) 
       references usuarios;

    alter table if exists mensajes_chat 
       add constraint FKoahqp00n8n95wohn7igsy8h6q 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists microciclo_grupos 
       add constraint FKlq0pv0p0hal9n07684m4lu567 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists microciclo_grupos 
       add constraint FK2488tj88k3sabqclp10u68n4k 
       foreign key (id_microciclo) 
       references microciclos;

    alter table if exists microciclo_pruebas 
       add constraint FK4jslaibno8inj2lm1s7uly8jt 
       foreign key (id_prueba) 
       references pruebas_estandar;

    alter table if exists microciclo_pruebas 
       add constraint FK1qg9j6fl2g8ah1lyxlj0syka5 
       foreign key (id_microciclo) 
       references microciclos;

    alter table if exists microciclos 
       add constraint FKgl69bfifkd2ycun2c3mpjj9c6 
       foreign key (id_macrociclo) 
       references macrociclos;

    alter table if exists microciclos 
       add constraint FKbibdxe2e91f5dokundnw6rah6 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists movimientos_caja 
       add constraint FK3cbjq01ktw6xn1i9wrhj5ro7y 
       foreign key (id_concepto) 
       references conceptos_financieros;

    alter table if exists movimientos_caja 
       add constraint FK8ia6bmifm9bkofnu597wsqqha 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists normas_evaluacion 
       add constraint FKrvvpbqrly11mu8oi8xe3v1ehk 
       foreign key (id_metrica) 
       references metricas;

    alter table if exists normas_evaluacion 
       add constraint FKhq6jhe9i9yr2iemvjxijn2f5r 
       foreign key (id_ejercicio) 
       references pruebas_estandar;

    alter table if exists pagos 
       add constraint FKbic1f9hi9n5h6dhjs7mqngusl 
       foreign key (id_cuenta_cobro) 
       references cuentas_cobro;

    alter table if exists pagos 
       add constraint FKgfmmy6lqyn1phcn713o95dcwk 
       foreign key (id_producto) 
       references productos;

    alter table if exists pagos 
       add constraint FKj6i33etwd3u7v8qf8asawa3bw 
       foreign key (id_usuario) 
       references usuarios;

    alter table if exists palmares 
       add constraint FK88ynbpiv35fymd3bvh2rlqymv 
       foreign key (id_competencia) 
       references competencias;

    alter table if exists palmares 
       add constraint FKrair2na6em11djlg1vsro42kq 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists plan_tarea_dias 
       add constraint FKmf4656rlwvtm36wckwi4iv9to 
       foreign key (id_ejercicio_plan) 
       references ejercicios_planificados;

    alter table if exists prueba_estandar_metricas 
       add constraint FK6f6dbiyh9tm4o5nriusu3pecg 
       foreign key (id_metrica) 
       references metricas;

    alter table if exists prueba_estandar_metricas 
       add constraint FKlumo84wnnqwey5s6jcqv2s84f 
       foreign key (id_ejercicio) 
       references pruebas_estandar;

    alter table if exists pruebas_estandar 
       add constraint FKej87ojd5d3uhrmk2qked5l3wu 
       foreign key (id_sensei_creador) 
       references senseis;

    alter table if exists publicaciones 
       add constraint FKqxrm8afa0jonhttcm7oij1mtm 
       foreign key (id_autor) 
       references usuarios;

    alter table if exists publicaciones 
       add constraint FKpvq1751t2ydwufaj3ai529l85 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists reflexiones 
       add constraint FKkr7o0pjasayg4ugwxllwa7ijo 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists reglas_gamificacion 
       add constraint FKil2yre6v6s362b25ln06o8tpp 
       foreign key (insignia_id) 
       references insignias;

    alter table if exists reglas_gamificacion 
       add constraint FKsxsykqtar2ya4gyq0gydci7sp 
       foreign key (metrica_id) 
       references metricas;

    alter table if exists reglas_gamificacion 
       add constraint FK3lnd3bjtapd5g6yra0951pk0n 
       foreign key (sensei_id) 
       references senseis;

    alter table if exists resultados_pruebas 
       add constraint FKs96xo5ketccmny54pgqyp0o6g 
       foreign key (id_ejercicio_plan) 
       references ejercicios_planificados;

    alter table if exists resultados_pruebas 
       add constraint FKo0hmn9eps7ou5m2ae6k0j72xe 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists resultados_pruebas 
       add constraint FK7qm46ge4lv7lm1w6nu5evrlq1 
       foreign key (id_metrica) 
       references metricas;

    alter table if exists senseis 
       add constraint FKkvim56d336jcxew2ficqb13s1 
       foreign key (id_usuario) 
       references usuarios;

    alter table if exists sesiones_ejecutadas 
       add constraint FKkvrv1ou4cmrtf4oj1es9n28w3 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists sesiones_ejecutadas 
       add constraint FKmebeg71b0303nbwaj4a5s1js0 
       foreign key (id_microciclo) 
       references microciclos;

    alter table if exists sesiones_ejecutadas 
       add constraint FKenrrp6cw52frx7vsgn2a13pyf 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists sesiones_programadas 
       add constraint FKotyp4k12y14n7q0b7dpmjodbp 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists sesiones_programadas 
       add constraint FK8kxdyh71ue7rhqrqlrhofcnlo 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists tareas_diarias 
       add constraint FKlnl3dbxq609jba1fgnafn9u93 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists tokens_invitacion 
       add constraint FKnabw7y7jn7aueu6vssjs1erif 
       foreign key (id_grupo) 
       references grupos_entrenamiento;

    alter table if exists tokens_invitacion 
       add constraint FKjjk3fj2tjec5lew5hh8h91spa 
       foreign key (id_judoka) 
       references judokas;

    alter table if exists tokens_invitacion 
       add constraint FK1yhd1xipydo8a9uesld3or680 
       foreign key (id_sensei) 
       references senseis;

    alter table if exists tokens_invitacion 
       add constraint FKm0y8u9x7h8a3fgh7kmv06frkf 
       foreign key (id_usuario) 
       references usuarios;

    alter table if exists usuarios 
       add constraint FKg4wtrc1y0hompog56qxuw75j6 
       foreign key (id_grupo_tarifario) 
       references grupos_entrenamiento;

    alter table if exists usuarios 
       add constraint FKl08804rr427o39d44yn07t1o2 
       foreign key (id_sensei_invitador) 
       references senseis;

    alter table if exists usuarios_roles 
       add constraint FKhcbndx0dnk4c3ww8jfg98k7el 
       foreign key (id_rol) 
       references roles;

    alter table if exists usuarios_roles 
       add constraint FKt5th9sao5wjukq9ij7154ktuw 
       foreign key (id_usuario) 
       references usuarios;
