-- Versión 3: Poblar la biblioteca de Métricas (CORREGIDO)
INSERT INTO metricas (nombre_key, unidad) VALUES
('metrica.masa_corporal.nombre', 'kg'),
('metrica.estatura.nombre', 'cm'),
('metrica.distancia.nombre', 'cm'),
('metrica.tiempo_isometrico.nombre', 's'),
('metrica.repeticiones_dinamicas.nombre', 'reps'),
('metrica.rep_dinamicas_kg.nombre', 'reps/kg'),
('metrica.tiempo_iso_kg.nombre', 's/kg'),
('metrica.repeticiones_uchikomi.nombre', 'reps'),
('metrica.sjft_proyecciones_s1.nombre', 'reps'),
('metrica.sjft_proyecciones_s2.nombre', 'reps'),
('metrica.sjft_proyecciones_s3.nombre', 'reps'),
('metrica.sjft_proyecciones_total.nombre', 'reps'),
('metrica.sjft_fc_final.nombre', 'bpm'),
('metrica.sjft_fc_1min.nombre', 'bpm'),
('metrica.sjft_indice.nombre', 'índice'),
('metrica.distancia_6min.nombre', 'm'),
('metrica.flexibilidad_sit_reach.nombre', 'cm'),
('metrica.abdominales_1min.nombre', 'reps'),
('metrica.lanzamiento_balon.nombre', 'cm'),
('metrica.agilidad_4x4.nombre', 's'),
('metrica.velocidad_20m.nombre', 's'),
('metrica.imc.nombre', 'kg/m²'),
('metrica.whtr.nombre', 'ratio');